export async function GET() {
  const tickets = [
    {
      id: 't-1001',
      title: 'Cannot connect to VPN',
      description: 'User reports intermittent VPN connectivity errors.',
      priority: 'High',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-10-31T14:05:00Z',
    },
    {
      id: 't-1002',
      title: 'Email not synching on mobile',
      description: 'Outlook mobile app not receiving new emails.',
      priority: 'Medium',
      status: 'In Progress',
      assignee: 'Ben Johnson',
      updatedAt: '2025-11-01T09:03:00Z',
    },
    {
      id: 't-1003',
      title: 'Printer server down',
      description: 'Users report printer connectivity errors.',
      priority: 'Low',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-10-29T16:27:00Z',
    },
    {
      id: 't-1004',
      title: 'Password reset request',
      description: 'User cannot access account.',
      priority: 'Medium',
      status: 'Resolved',
      assignee: 'Lisa Simpson',
      updatedAt: '2025-12-13T21:07:00Z',
    },
    {
      id: 't-1005',
      title: 'Overheating laptop',
      description: 'Laptop overheats during Zoom calls.',
      priority: 'High',
      status: 'In Progress',
      assignee: 'Patty Patrickson',
      updatedAt: '2025-09-11T23:25:00Z',
    },
    {
      id: 't-1006',
      title: 'WiFi deadzone in Oval Office',
      description: 'Weak signal in Oval Office.',
      priority: 'Critical',
      status: 'In Progress',
      assignee: 'Ethan Counasse',
      updatedAt: '2025-11-17T23:12:00Z',
    },
    {
      id: 't-1007',
      title: 'Database connection timeout',
      description: 'App cannot connect to the SQL database.',
      priority: 'Medium',
      status: 'Resolved',
      assignee: 'Marcus Freeman',
      updatedAt: '2025-02-07T01:05:00Z',
    },
    {
      id: 't-1008',
      title: 'Teams audio devices not detected',
      description: 'Headset intermittently disconnects.',
      priority: 'Low',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-04-04T16:04:00Z',
    },
    {
      id: 't-1009',
      title: 'MacOS upgrade request',
      description: 'User wants to upgrade to latest macOS.',
      priority: 'Medium',
      status: 'In Progress',
      assignee: 'Patrick Wilson',
      updatedAt: '2025-09-02T06:11:00Z',
    },
    {
      id: 't-1010',
      title: 'AI Bot not responding',
      description: 'AI Bot fails to post reminders.',
      priority: 'Medium',
      status: 'Resolved',
      assignee: 'Jerry Jones',
      updatedAt: '2025-11-03T10:01:00Z',
    },
    {
      id: 't-1011',
      title: 'Security alert',
      description: 'Multiple failed login attempts from foreign IP.',
      priority: 'High',
      status: 'On Hold',
      assignee: 'Kenny Thompson',
      updatedAt: '2025-07-11T21:12:00Z',
    },
    {
      id: 't-1012',
      title: 'Broken HDMI port in meeting room',
      description: 'Cannot connect laptop to TV.',
      priority: 'Low',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-10-10T10:10:00Z',
    },
  ];

  return Response.json(tickets);
}
